projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://hackernews-gql.herokuapp.com/
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml